### PR TITLE
Cloud9 deployment

### PR DESCRIPTION
**Pull request by malte-aws**
*Description of changes:*
- Adds step-by-step instructions on deploying with AWS Cloud9
- Enable document ingestion from local disk
- Enable document ingestion from URL, for example Amazon S3
- Upgrades Haystack to v1.16.0 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by liyudo** [comment]
Hi Malte, I came across your pull request yesterday and I want to thank you for the excellent work you have put into it. 

However, I've encountered some difficulty in understanding the instructions provided for "Ingesting your own documents". Specifically, I am unsure about the process of setting up the backend for the application when using my own files for embeddings.

As I understand it, the first step would seem to be to upload the required files into the /semantic-search-aws-docs/ingestion/awsdocs/data directory. However, the subsequent steps are somewhat unclear to me.

I kindly request if you could update your instructions with a more detailed guide on how to use local files for the application. This additional clarification would greatly assist me, and likely others, in utilizing this application to its full potential.

I sincerely appreciate your time and consideration, and once again, thank you for your outstanding work on this repository!

**Comment by malte-aws** [comment]
Hi @liyudo,

I updated the instructions to include step-by-step instructions on how to ingest your own documents. You find the updated instructions on my cloud9-deployment branch: [https://github.com/malte-aws/semantic-search-aws-docs/blob/cloud9-deployment/documentation/aws-cloud9-deployment.md](https://github.com/malte-aws/semantic-search-aws-docs/blob/cloud9-deployment/documentation/aws-cloud9-deployment.md)

Could you please take a look at the instructions and give me feedback?

Where do you store the documents that you want to make searchable today? Do you store the documents on your local drive? Right now the instructions explain how to ingest the documents from your local drive. The way it is set up right now uploads the local documents into the docker container that runs the ingestion. This might run into scalability issues if there are many documents. I am considering rewriting the process to use Amazon S3.

**Review by ArlindNocaj — APPROVED** [review]
tested with cpu only mode and ingestion of local documents, applied a couple of fixes.

**Comment by ArlindNocaj** [comment]
@liyudo it would be great if you could try out the new version with ingestion of local documents and provide feedback, e.g. also on the documentation.

**Comment by liyudo** [comment]
hi @ArlindNocaj and @malte-aws, 

Thanks so much for the great work! I deployed it and imported some files locally last week (haven't had time to try out the S3 version) the documentation is easy to follow and the feasibility to change the number of answers and documents is a great idea. However, the result of the answer is not so accurate, it was not able to find the correct result, so it would be great if the documentation can explain how to change the model for the retriever and reader, or just set models as a parameter so user can choose it themselves.

**Comment by malte-aws** [comment]
Hi @liyudo,

thank you for giving it a go and providing feedback. You are right, the [Bart_lafq](https://huggingface.co/vblagoje/bart_lfqa) is not state of the art anymore. I'll start writing instructions to use a recent model.

**Pull request merged**
